

* Introduction

The interaction of unsaturated hydrocarbons on metallic surfaces has been the subject of considerable interest in the field of surface chemistry and catalysis over the years. Advances in computer power and the development of efficient first-principles electronic structure methods have given the theoretical treatment of surface structures a tremendous boost. Recent Density Functional Theory(DFT) studies have helped bring insight and answer key questions about the adsorption of hydrocarbons like acetylene, ethylene, benzene, etc on different metal substrates\cite{tri}. A large number of experimental and theoretical studies have been performed with an aim to developing cheaper, more active, more selective and longer lasting catalysts from those currently in use.

The present work covers a review of two DFT studies\cite{val,mit} which together give a detailed picture of the adsorption of hydrocarbons like 1,3 butadiene and 1-butene on Pd(111) and Pd(111) surfaces. These have been chosen as they have been investigated to a much lesser extent compared to those listed above.

Intrigued by observations that the palladium catalyst is more active and more selective than platinum, Valcarcel et al.\cite{val} compared adsorption geometries, binding site preference and adsorption energies of 1,3-butadiene, 1-butene and 2-cis/trans butene on Pd(111) and Pt(111) in an attempt to accurately understand the surface process. At around the same time, a  parallel study was performed by Mittendorfer et al.\cite{mit} in order to find the adsorption strengths for a wide range of hydrocarbons.

* Methods

Both Mittendorfer et al. and Valcarcel et al. have performed calculations using the Vienna Ab-initio Simulation Program(VASP). The electonic wave functions have been expanded into plane waves upto a cutoff energy of 400 eV. The projector augmented wave method (PAW) and the Perdew-Wang gradient corrections have been used. Mittendorfer has performed the Brillouin-zone integration with a 7x7x1 Monkhorst Pack grid and a Methfessel-Paxton smearing of 0.1 eV at different coverages while Valcarcel uses 4 different unit cells at different coverages. For the solid surface a four-layer slab has been used when the k-point convergence is reached with the hydrocarbon molecules adsorbed on one side of the slabs. A geometry relaxation has been performed for all degrees of freedom of the adsorbate and for the uppermost two layers of the metal surface by Valcarcel and on the uppermost layer by Mittendorfer et al.

* Findings

The results in both works have been found to be more or less consistent throughout and are close to previous experimental\cite{cam} and theoretical studies\cite{mare}. Among the different structures of 1,3-butadiene tested on the Pt(111) surface the two most stable adsorption modes are found to be the 1,2,3,4-tetra-\sigma and the 1,4-di-\sigma-2,3-\pi. These structures differ only by 10 kJ/mol and because of the approximations involved in the calculation of exchange correlation energies in the GGA-DFT, definite conclusions cannot be drawn regarding which is more stable. In order to find a clear answer simulated vibrational spectra have been compared to the experimental electron energy loss spectroscopy(EELS) spectrum\cite{avery} for the adsorbed 1,3-butadiene molecule. The tetra-\sigma mode shows close resemblence to the experimental spectrum and can be concluded to be the majority species on the surface.However, the 1,4-di-\sigma-2,3-\pi cannot be neglected completely as its presence as a minority helps explain the enhancement of a few peaks on the spectra.

For adsorption on Pd(111), it has been seen that the \pi modes are more stablilized compared to the Pt which shows \sigma adsorption. Largely similar adsorption energies(which reduce at lower coverages) for both Pd and Pt surfaces are seen in both reports. The configurations are seen to be much less distorted on the Pd surface than on the Pt one. Also, \pi adsorption modes are less destabilized as compared to \sigma modes on Pd(111). As a consequence, the energy difference between the di-\sigma and \pi modes is smaller on Pd.

The strength of 1-butene adsorption is found to exhibit a similar trend when compared to 1,3-butadiene. The adsorption energy is found to be lower for 1-butene than for ethylene which is to be expected owing to its larger molecular size and deformation energy. For adsorption on Pt(111) it is clear that the di-\sigma mode is more favorable. On Pd(111), the difference in adsorption energies di-\sigma and \pi modes is much smaller compared to Pt. This partial \pi character for Pd and increased \sigma character for Pt consistent with experimental results\cite{bert,trou}.



* Discussion and Review

Both sets of research groups have taken a comprehensive DFT based approach. They have adequately checked for convergence and have elaborately detailed their computational approach. Their results have been fairly consistent with experimental findings. Some findings have reported that the di-\sigma mode is most stable on the Pt surface and not the tetra-\sigma one. The theoretical basis for the analysis however, appears to be sound and both Valcarcel et al. and Mittendorfer et al. have reported that the tetra-\sigma structure is more stable by around 20 kJ/mol.

Similarly for 1-butene, the theoretical approach shows that for both Pt and Pd, the di-\sigma adsorption mode is more favorable. Experimental findings had previously predicted this to be the case for Pt but not for Pd, where a \pi mode was expected.

An answer to why selectivity of Pt is found to be lower than Pd is not clear. However, it can in part, be attributed to the lower stability of 1-butene on Pd as compared to Pt. A study of the stability of reaction intermediates has been proposed towards finding a definitive answer.


\begin{thebibliography}{99}
\bibitem{tri} L. Triguero, L.G.M.Patterson, {\em J. Chem. Phys.} \textbf{108}, 1193 (1998).
\bibtem{val} A. Valcarcel et al. {\em Surface Science} \textbf{549}, 121 (2004).
\bibitem{mit} Mittendorfer et al. {\em J. Phys. Chem.} \textbf{107}, 12289 (2003).
\bibitem{cam}
